chore: added StackSpot study plan for non-developers
zup-academy/planos-estudos-zup pull request #7
Opened 2023-03-17 21:39 UTC by dearrudam

Added a new study plan about StackSpot for non-developers

2023-03-20 14:02 UTC, albertotavareszup approved these changes
@lucassampaiozup @jacksonmotazup vocês sobem esse plano aqui?

2023-03-20 17:40 UTC, jacksonmotazup requested changes
por favor, adicione o titulo do plano no arquivo (se possível em portugues para facilitar a busca, a não ser que queira realmente deixar em inglês).
além disso, cada tema(referencia) tem que ter um objetivo de aprendizagem. 
A lista de objetivos de aprendizagem são tiradas de cada tema, não precisa informar ela.
Os conteudos adicionais vão entrar como temas comuns, e cada um precisa ter um objetivo proprio também.

2023-03-20 17:40 UTC, jacksonmotazup commented on stackspot/stk-4-non-dev.md
> +  - Objetivo de aprendizagem: Conhecer a plataforma StackSpot, o que ela é a plataforma, principais conceitos, para que ela foi criada, como ela funciona e quais as ferramentas/funcionalidades que a
é para adicionar esse objetivo para todos os temas(referencias)?

2023-03-20 18:43 UTC, jacksonmotazup commented on stackspot/stk-4-non-dev.md
> +  - Objetivo de aprendizagem: Conhecer a plataforma StackSpot, o que ela é a plataforma, principais conceitos, para que ela foi criada, como ela funciona e quais as ferramentas/funcionalidades que a
ah entendi, então todas essas 11 referencias estão nesse primeiro tema. blz, entendi agora, mt obrigado!

2023-03-20 19:00 UTC, jacksonmotazup approved these changes

2023-03-24 21:00 UTC, albertotavareszup reviewed
@jacksonmotazup , esse aqui já foi importado?

2023-03-31 11:31 UTC, merged