Adiciona plano de estudos para iOS Development Fundamentals
zup-academy/planos-estudos-zup pull request #8
Opened 2023-03-24 20:07 UTC by rafaelrollozup

Este PR adiciona uma proposta de plano de estudos para iOS, em linha com o conteúdo da avaliação **Knowledge about iOS Development Fundamentals**.

2023-03-24 20:59 UTC, albertotavareszup reviewed
@jacksonmotazup @lucassampaiozup Podem ver aqui?

2023-03-30 19:45 UTC, albertotavareszup commented
@jacksonmotazup @lucassampaiozup Precisamos subir isso aqui

2023-03-31 11:31 UTC, jacksonmotazup commented on ios/ios-development-fundamentals.md
> +
Rafael, vc pode adicionar o titulo aqui no arquivo tbm? tenho receio de tirar ali do nome do arquivo e pegar mais ou menos do que vc gostaria.

2023-03-31 12:31 UTC, jacksonmotazup commented on ios/ios-development-fundamentals.md
> +
opa, reparei que as referencias desse plano estão sem link, vc consegue colocar, por favor?

2023-03-31 12:32 UTC, jacksonmotazup requested changes
deixei dois comentários nesse

2023-03-31 13:20 UTC, rafaelrollozup commented on ios/ios-development-fundamentals.md
> +
Fala Jackson, claro mano. Comi bola, esqueci do título nos planos. Já to ajustando..

2023-03-31 13:20 UTC, rafaelrollozup commented on ios/ios-development-fundamentals.md
> +
Farei tb, esqueci nesse

2023-03-31 13:36 UTC, rafaelrollozup commented
Feito, @jacksonmotazup ✌🏻

2023-03-31 13:38 UTC, jacksonmotazup commented
perfeito, vou subir e mergear assim que subir. te aviso, obrigado.

2023-03-31 17:40 UTC, jacksonmotazup approved these changes

2023-03-31 17:40 UTC, merged