Adiciona plano de estudos para iOS Application Security
zup-academy/planos-estudos-zup pull request #9
Opened 2023-03-30 16:32 UTC by rafaelrollozup

Este PR adiciona uma proposta de plano de estudos para iOS App Security, em linha com o item **Application Security** da colmeia da Zup.

O plano indica materiais educacionais das plataformas Kodeco.com e Oreilly Learning.

2023-03-30 19:44 UTC, albertotavareszup reviewed
@jacksonmotazup @lucassampaiozup Vocês revisam e sobem aqui?

2023-03-31 11:27 UTC, jacksonmotazup requested changes

2023-03-31 11:27 UTC, jacksonmotazup commented on ios/ios-security.md
> +
@rafaelrollozup , primeiro desculpe a demora para ver os seus PRs, hehe
vc poderia adicionar o titulo aqui no arquivo, por favor?

2023-03-31 11:27 UTC, jacksonmotazup commented on ios/ios-security.md
> +* Quanto à usabilidade das aplicações
eu vi que tem alguns temas que me parece ter dois títulos, ou um título e um subtitulo. vc pode me explicar qual seria o titulo do tema, ou editar deixando apenas um, por favor?

2023-03-31 13:37 UTC, rafaelrollozup commented on ios/ios-security.md
> +
Que isso mano, fica tranquilo! Vou adicionar aqui também.

2023-03-31 13:54 UTC, rafaelrollozup commented on ios/ios-security.md
> +* Quanto à usabilidade das aplicações
Então @jacksonmotazup, aqui eu fiquei na dúvida na estrutura mesmo. Eu pensei (pq acho que vi isso em algum plano de estudo, se não tiver enganado) de ter uma estrutura de navegação multinível, algo do tipo

```
-- Quanto à usabilidade das aplicações (card que navega pra estrutura inferior)
     -- Storage seguro e criptografia de dados (card que navega pra estrutura inferior)
          -- Item que indica uma referência de fato 1 (card que ao clicar navega para o material)
          -- Item que indica uma referência de fato 2 (card que ao clicar navega para o material)

     -- Componentes de alto nível para autenticação
          -- Item que indica uma referência de fato 1 (card que ao clicar navega para o material)
          -- Item que indica uma referência de fato 2 (card que ao clicar navega para o material)

-- Quanto às defesas a possíveis atacantes de uma aplicação
      -- Sobre o contexto de segurança na distribuição de aplicações iOS
          -- Item que indica uma referência de fato 1 (card que ao clicar navega para o material)
          -- Item que indica uma referência de fato 2 (card que ao clicar navega para o material)
      
     -- Sobre como é possível conduzir ataques e testes à segurança de uma aplicação iOS
          -- Item que indica uma referência de fato 1 (card que ao clicar navega para o material)
          -- Item que indica uma referência de fato 2 (card que ao clicar navega para o material)

     -- Sobre as estratégias de defesa à exploração de vulnerabilidades de segurança
          -- Item que indica uma referência de fato 1 (card que ao clicar navega para o material)
          -- Item que indica uma referência de fato 2 (card que ao clicar navega para o material)
```

É possível atingir isso mesmo, ou eu viajei na maionese aqui? Se não rolar um busco outra forma de organizar esses itens hierarquicamente.

2023-03-31 14:02 UTC, jacksonmotazup commented on ios/ios-security.md
> +* Quanto à usabilidade das aplicações
então, é pq é assim, temos os temas, cada tema tem um titulo e um conjunto de referencias, cada referencia tem um titulo e uma url. nesse formato que vc fez, me pareceu que o tema tem titulo e subtitulo, e isso o nosso sistema não suporta mesmo. 
(inclusive fiz um template novo atualizado, depois se quiser dar uma olhada: https://github.com/zup-academy/planos-estudos-zup/blob/master/template-cria%C3%A7%C3%A3o-plano/template-cria%C3%A7%C3%A3o-plano-estudo.md)
mas por enquanto, se vc puder deixar apenas um titulo por tema, infelizmente não suportamos desse jeito mesmo :/

2023-03-31 14:05 UTC, rafaelrollozup commented on ios/ios-security.md
> +* Quanto à usabilidade das aplicações
Beleza, valeu por mandar o template. To dando uma olhada nele por aqui e ja subo uma atualização.

2023-03-31 15:29 UTC, rafaelrollozup commented
Feito, @jacksonmotazup. Foi mal a demora.

2023-03-31 17:40 UTC, merged